namespace Karen90MmoFramework.Rpc
{
	public enum ResultCode : short
	{
		InvalidOperationCode				= -5,
		OperationNotAvailable				= -4,
		InvalidOperationParameter			= -3,
		InvalidParameterType				= -2,
		Fail								= -1,
		Ok									= 0,
											
		ServerNotFound						= 1,
		ResendRequestInternal				= 2, // resend the request within the server
		ResendRequestExternal				= 3, // resend the request from the client
		AlreadyRegistered					= 4,
		ChannelCreationFailed				= 5,
		UserAlreadyLoggedIn					= 6,
		UserAlreadyPlaying					= 7,
		ClientNotAuthorized					= 8,
		ZoneServerOffline					= 9,
		ClientNotFound						= 10,
		InvalidRegisterationCredentials		= 11,

		// login
		IncorrectUsernameOrPassword,
		UsernameAlreadyExists,
		CharacterNameAlreadyExists,
		UsernameIsEmpty,
		UsernameIsTooShort,
		PasswordIsEmpty,
		PasswordIsTooShort,
		CharacterNameIsEmpty,
		CharacterNameIsTooShort,
		CharacterNameIsTooLong,
		InvalidClass,
		InvalidRace,
		InvalidOrigin,
		// world
		WorldNotFound,
		ObjectNotFound,
		InsufficentFund,
		InventoryFull,
		ItemUseFailed,
		ItemNotFound,
		PlayerNotFound,
		PlayerIsOffline,
		ObjectIsOutOfRange,
		CannotInteractWhileDead,
		ObjectIsBusy,
		NoLootAvailable,
		InteractorNotFound,
		InteractorNotAMerchant,
		InvalidQuantity,
		ActionNotAvailable,
		CannotSellQuestItem,
		CannotUseItem,
		InteractorIsDead,
		// group
		CannotInviteSelf,
		YourAlreadyInAGroup,
		PlayerAlreadyInAGroup,
		PlayerIsBusy,
		InteractionNotAvailable,
		NoInvitationFound,
		GroupIsFull,
		YouAreNotInAGroup,
		YouAreNotTheLeader,
		CannotJoinGroup,
		MemberNotFound,
		// quest
		YouAreTooLowForThisQuest,
		CannotAcceptQuestWhileDead,
		NoQuestAvailable,
		QuestGiverIsDead,
		QuestNotFound,
		QuestAlreadyCompleted,
		QuestAlreadyAccepted,
		QuestRequirementNotMet,
		QuestJournalFull,
		QuestNotCompleted,
		// chat
		MessageIsEmpty,
		ChannelNotAvailable,
		// social
		CannotFriendSelf,
		FriendAlreadyAdded,
		PlayerIsIgnored,
		AlreadySentRequest,
		AlreadyReceivedRequest,
		DeclinedRequest,
		NoRequestFound,
		// spell
		ObjectIsTooClose,
		NotEnoughPower,
		TargetIsDead,
		CasterIsDead,
		TargetRequired,
		InvalidTarget,
		SpellNotReady,
		SpellNotFound,
		SpellInCooldown,
		AlreadyCasting,
	}
}
